import React, { useState } from "react";
import {
  CandyAlert, CandyAvatar, CandyBreadcrumb, CandyButton, CandyCard, CandyColorPicker,
  CandyDatePicker, CandyDropdown, CandyEmptyState, CandyFileUpload, CandyGameIcon,
  CandyNavigation, CandyNotification, CandyPagination, CandyProgress, CandyRoomCard,
  CandySocialButton, CandySocialProvider, CandyStatusBadge, CandyStepper, CandySteps,
  CandyTagInput, CandyThemeGrid, CandyTimePicker,
  useCandyToast,
} from "candy-ui";
import { gameNavigation, themeDefinitions, themeOptions } from "./gameKitData";
import "../styles/reference-docs.css";

export const referenceCatalog = [
  { id: "game-cards", name: "Game cards", component: "CandyCard / CandyRoomCard", description: "Reusable game surfaces and room cards with capacity-aware join actions and labelled connection strength.", props: [["title", "ReactNode", "—", "Card or room heading."], ["icon / footer", "ReactNode", "—", "Composable artwork and actions."], ["players / capacity", "number", "required for room", "Full rooms automatically disable joining."], ["connection", "'good' | 'fair' | 'poor' | 'offline'", "'good'", "Signal icon and accessible connection label."], ["compact", "boolean", "false", "Switch to a room-list row."], ["onJoin", "() => void", "—", "Join callback; no network service is included."]] },
  { id: "theme-grid", name: "Theme selection", component: "CandyThemeCard / CandyThemeGrid", description: "Original illustrated theme cards with controlled selection, native keyboard activation and a visible selection check.", props: [["options", "CandyThemeOption[]", "required", "Value, label, artwork and optional disabled state."], ["value / defaultValue", "string", "—", "Controlled or initial selected theme."], ["onChange", "(value: string) => void", "—", "Receives the selected theme identifier."], ["columns", "number", "auto-fit", "Explicit column count when needed."], ["disabled", "boolean", "false", "Disables all choices."]] },
  { id: "status-badges", name: "Status badges", component: "CandyStatusBadge", description: "Player presence, roles and capacity states with both a symbol and readable text.", props: [["status", "CandyStatus", "'online'", "online, playing, offline, away, host, admin or full."], ["label / children", "ReactNode", "status label", "Custom or localized visible label."], ["icon", "ReactNode", "status symbol", "Override the leading symbol."], ["size", "'sm' | 'md'", "'md'", "Badge scale."]] },
  { id: "alerts", name: "Alerts", component: "CandyAlert", description: "Inline, dismissible feedback with semantic status colors, a matching icon and appropriate announcement roles.", props: [["tone", "'success' | 'info' | 'warning' | 'error'", "'info'", "Message severity."], ["title / children", "ReactNode", "—", "Heading and optional supporting message."], ["action", "ReactNode", "—", "Optional action content."], ["onClose", "() => void", "—", "Dismiss callback; remove the alert in your state."], ["closeLabel", "string", "'Dismiss alert'", "Localized accessible close label."]] },
  { id: "navigation", name: "Navigation", component: "CandyNavigation", description: "Horizontal game navigation or a vertical sidebar using native links and buttons, rather than tab semantics.", props: [["items", "CandyNavigationItem[]", "required", "value, label, icon, href and disabled options."], ["value", "string", "—", "Marks the current page with aria-current."], ["onChange", "(value: string) => void", "—", "Select a destination."], ["orientation", "'horizontal' | 'vertical'", "'horizontal'", "Navigation or sidebar layout."], ["brand / footer", "ReactNode", "—", "Optional composition slots."]] },
  { id: "breadcrumbs", name: "Breadcrumbs", component: "CandyBreadcrumb", description: "Small, accessible navigation trails with native links, optional actions and an identified current location.", props: [["items", "CandyBreadcrumbItem[]", "required", "label, href, icon and optional onClick."], ["separator", "ReactNode", "chevron", "Custom decorative separator."], ["aria-label", "string", "'Breadcrumb'", "Names this navigation landmark."]] },
  { id: "pagination", name: "Pagination", component: "CandyPagination", description: "A bounded page selector with ellipses, disabled edge actions and an accessible current-page marker.", props: [["page", "number", "required", "One-based current page; invalid values are clamped."], ["totalPages", "number", "required", "Total available pages."], ["onPageChange", "(page: number) => void", "required", "Receives the requested page."], ["siblingCount", "number", "1", "Number of neighboring page buttons."], ["size", "'sm' | 'md' | 'lg'", "'md'", "Control scale."]] },
  { id: "steps", name: "Steps", component: "CandySteps", description: "Labelled setup steps with completed, current and upcoming states. Make them interactive only when the flow permits it.", props: [["items", "CandyStepItem[]", "required", "Label, optional description/icon and disabled state."], ["current", "number", "required", "Zero-based step; items.length marks every step complete."], ["onStepChange", "(index: number) => void", "—", "Enables native step buttons."], ["orientation", "'horizontal' | 'vertical'", "'horizontal'", "Step layout."]] },
  { id: "dropdowns", name: "Dropdown menus", component: "CandyDropdown", description: "Action menus with arrow-key navigation, typeahead, outside dismissal and focus restoration. The trigger must forward its DOM ref and event props.", props: [["trigger", "ReactElement", "required", "A native button or ref-forwarding component such as CandyButton."], ["items", "CandyDropdownItem[]", "required", "id, label, icon, onSelect, disabled, destructive and separator."], ["open / defaultOpen", "boolean", "false", "Controlled or initial visibility."], ["onOpenChange", "(open: boolean) => void", "—", "Visibility callback."], ["align", "'start' | 'end'", "'start'", "Menu alignment; clipping ancestors can clip inline menus."]] },
  { id: "stepper", name: "Number stepper", component: "CandyStepper", description: "A native numeric field with increment/decrement actions, decimal steps, typed drafts and lower/upper limits.", props: [["value / defaultValue", "number", "0", "Controlled or initial numeric value."], ["onChange", "(value: number) => void", "—", "Receives a finite, bounded value."], ["min / max / step", "number", "0 / Infinity / 1", "Numeric limits and increment."], ["label", "ReactNode", "—", "Associated field label."], ["disabled / readOnly", "boolean", "false", "Prevents edits and button activation."]] },
  { id: "tag-input", name: "Tag input", component: "CandyTagInput", description: "Add tags with Enter, remove them with a button or Backspace, and prevent duplicates or excessive lengths.", props: [["value / defaultValue", "string[]", "[]", "Controlled or initial tags."], ["onChange", "(tags: string[]) => void", "—", "Updated tags after adding or removing."], ["maxTags / maxTagLength", "number", "Infinity / 40", "Limits with inline validation feedback."], ["name", "string", "—", "Serializes each tag as a repeated form field."], ["removeLabel", "(tag: string) => string", "'Remove …'", "Localizes each remove action."]] },
  { id: "upload", name: "File upload", component: "CandyFileUpload", description: "Keyboard-accessible selection and drag-and-drop with file type, byte size and count validation. Files stay local; no network upload is performed.", props: [["accept", "string", "—", "Native file types, MIME wildcards or extensions."], ["maxSize", "number", "10485760", "Maximum file size in bytes."], ["multiple / maxFiles", "boolean / number", "false / Infinity", "Multiple-file selection and count limit."], ["onFilesChange", "(files: File[]) => void", "—", "Receives accepted files, including an empty list."], ["onError", "(message: string, file?: File) => void", "—", "Reports rejected selections."]] },
  { id: "date-time", name: "Date & time", component: "CandyDatePicker / CandyTimePicker", description: "Styled native date and time inputs. The browser supplies its accessible picker and locale-specific display.", props: [["value / defaultValue", "string", "—", "ISO date or 24-hour time."], ["onChange", "ChangeEventHandler<HTMLInputElement>", "—", "Native input change event."], ["min / max / step", "native input attributes", "—", "Scheduling limits."], ["label / hint / error", "ReactNode", "—", "CandyInput field composition."]] },
  { id: "color-picker", name: "Color picker", component: "CandyColorPicker", description: "A native color swatch paired with a validated editable HEX value and dropdown preset palette. Supports 12 theme presets and custom color dialog.", props: [["value / defaultValue", "string", "'#0068f0'", "Current color as HEX."], ["onChange", "(hex: string) => void", "—", "Receives normalized six-digit HEX."], ["label / hexLabel", "ReactNode / string", "— / 'Hex color'", "Names the color and text inputs."], ["presets", "string[] | false", "12 theme colors", "Preset color palette in dropdown; set false to disable."], ["disabled / readOnly", "boolean", "false", "Prevents color changes."]] },
  { id: "empty-states", name: "Empty states", component: "CandyEmptyState", description: "A helpful empty state with optional artwork and a next action; equally at home in a lobby or inventory.", props: [["title", "ReactNode", "—", "Empty-state heading."], ["description", "ReactNode", "—", "Why the view is empty."], ["icon", "ReactNode", "default artwork", "Replace or hide the illustration."], ["action", "ReactNode", "—", "An actionable way forward."]] },
  { id: "notifications", name: "Notifications", component: "CandyNotification", description: "A composable notification surface with optional actions and dismissal. Use the toast provider for transient notifications.", props: [["title / description", "ReactNode", "—", "Notification content."], ["icon / action", "ReactNode", "—", "Illustration and action slots."], ["onClose", "() => void", "—", "Dismiss callback."], ["closeLabel", "string", "'Dismiss notification'", "Accessible close label."]] },
  { id: "social-buttons", name: "Social buttons", component: "CandySocialButton", description: "Recognizable provider buttons, built on CandyButton. Supply your own authentication handler; the library never contacts a provider.", props: [["provider", "'twitter' | 'google' | 'vk' | 'discord'", "required", "Brand icon, label and palette."], ["children", "ReactNode", "provider name", "Custom action label."], ["size / appearance / loading", "CandyButton props", "button defaults", "Same sizing, surface and pending state as buttons."], ["onClick", "MouseEventHandler", "—", "Your application action."]] },
];

export const referenceSnippets: Record<string, string> = {
  "game-cards": `<CandyRoomCard\n  title="快乐涂鸦房"\n  icon={<CandyGameIcon name="fox" size={32} />}\n  players={8} capacity={15} connection="good"\n  joinLabel="加入" onJoin={() => joinRoom()}\n/>`,
  "theme-grid": `const [theme, setTheme] = useState("fox");\n\n<CandyThemeGrid value={theme} onChange={setTheme}\n  aria-label="Choose a theme"\n  options={[\n    { value: "fox", label: "动物", icon: <CandyGameIcon name="fox" size={32} /> },\n    { value: "star", label: "食物", icon: <CandyGameIcon name="star" size={32} /> },\n  ]}\n/>`,
  "status-badges": `<CandyStatusBadge status="online" label="在线" />\n<CandyStatusBadge status="host" label="房主" />\n<CandyStatusBadge status="full" label="已满" />`,
  "alerts": `const [visible, setVisible] = useState(true);\n\n{visible && <CandyAlert tone="success" title="Room created!"\n  onClose={() => setVisible(false)}\n/>}`,
  "navigation": `<CandyNavigation value={page} onChange={setPage}\n  orientation="horizontal" aria-label="Game navigation"\n  items={[\n    { value: "home", label: "Home", icon: <CandyGameIcon name="home" /> },\n    { value: "rooms", label: "Rooms", icon: <CandyGameIcon name="controller" /> },\n  ]}\n/>`,
  "breadcrumbs": `<CandyBreadcrumb items={[\n  { label: "Home", href: "/" },\n  { label: "Settings", onClick: () => openSettings() },\n  { label: "Themes" },\n]} />`,
  "pagination": `const [page, setPage] = useState(1);\n\n<CandyPagination page={page} totalPages={10}\n  onPageChange={setPage} siblingCount={1}\n/>`,
  "steps": `<CandySteps current={step} onStepChange={setStep}\n  items={[{ label: "Configure" }, { label: "Theme" }, { label: "Done" }]}\n/>`,
  "dropdowns": `<CandyDropdown\n  trigger={<CandyButton>Player menu</CandyButton>}\n  items={[\n    { id: "edit", label: "Edit profile", onSelect: openProfile },\n    { id: "logout", label: "Sign out", destructive: true, separator: true, onSelect: signOut },\n  ]}\n/>`,
  "stepper": `const [seconds, setSeconds] = useState(180);\n\n<CandyStepper label="Round duration" value={seconds}\n  onChange={setSeconds} min={30} max={300} step={10}\n/>`,
  "tag-input": `const [tags, setTags] = useState(["游戏", "动漫"]);\n\n<CandyTagInput label="Favorite themes" value={tags}\n  onChange={setTags} maxTags={6} maxTagLength={12} name="themes"\n/>`,
  "upload": `<CandyFileUpload accept="image/png,image/jpeg"\n  maxSize={10 * 1024 * 1024} multiple maxFiles={3}\n  onFilesChange={setFiles}\n  description="PNG or JPG, up to 10 MB"\n/>`,
  "date-time": `<CandyDatePicker label="Date" defaultValue="2026-10-05"\n  onChange={(event) => setDate(event.target.value)}\n/>\n<CandyTimePicker label="Time" defaultValue="12:30" />`,
  "color-picker": `const [color, setColor] = useState("#0068f0");\n\n<CandyColorPicker label="Theme color" value={color}\n  onChange={setColor} hexLabel="Theme HEX value"\n/>`,
  "empty-states": `<CandyEmptyState title="No rooms yet"\n  description="Create the first one and invite a friend."\n  icon={<CandyGameIcon name="controller" size={48} />}\n  action={<CandyButton onClick={createRoom}>Create room</CandyButton>}\n/>`,
  "notifications": `<CandyNotification title="New message"\n  description="Your friends are ready to play."\n  onClose={dismiss}\n  action={<CandyButton variant="ghost" onClick={readMessages}>Read messages</CandyButton>}\n/>`,
  "social-buttons": `<CandySocialButton provider="discord"\n  onClick={handleDiscordLogin}>Continue with Discord</CandySocialButton>\n\n// Your app supplies the authentication flow.`,
};

export function ReferenceComponentPreview({ id }: { id: string }) {
  const { showToast } = useCandyToast();
  const [theme, setTheme] = useState("fox");
  const [nav, setNav] = useState("home");
  const [page, setPage] = useState(3);
  const [step, setStep] = useState(1);
  const [seconds, setSeconds] = useState(180);
  const [tags, setTags] = useState(["游戏", "动漫", "食物"]);
  const [color, setColor] = useState("#0068f0");
  const [alertVisible, setAlertVisible] = useState(true);
  const [notificationVisible, setNotificationVisible] = useState(true);
  const [files, setFiles] = useState<File[]>([]);
  const [date, setDate] = useState("2026-10-05");
  const [time, setTime] = useState("12:30");
  const toast = (title: string) => showToast({ title, variant: "blue" });
  if (!referenceSnippets[id]) return null;

  return <div className="reference-preview" data-reference-preview={id}>
    {id === "game-cards" && <div className="reference-two-columns"><CandyRoomCard title="快乐涂鸦房" theme="动物" players={8} capacity={15} icon={<CandyGameIcon name="fox" size={40} color="var(--candy-primary)" />} joinLabel="加入房间" connectionLabel="连接良好" onJoin={() => toast("加入房间：本地演示")} /><CandyCard title="涂鸦大师" description="赢得 10 场比赛" icon={<CandyGameIcon name="trophy" size={34} color="#d69c00" />} footer={<CandyButton size="sm" variant="yellow" onClick={() => toast("成就详情")}>查看成就</CandyButton>}><CandyProgress aria-label="Achievement progress" value={6} max={10} striped height={18} /></CandyCard></div>}
    {id === "theme-grid" && <><CandyThemeGrid aria-label="Docs theme selection" value={theme} onChange={setTheme} options={themeOptions()} columns={4} /><p className="reference-hint" role="status">Selected theme: {theme}</p></>}
    {id === "status-badges" && <div className="reference-row">{(["online", "playing", "offline", "away", "host", "admin", "full"] as const).map((status) => <CandyStatusBadge key={status} status={status} />)}</div>}
    {id === "alerts" && <><CandyAlert tone="info" title="正在加入游戏…" /><CandyAlert tone="warning" title="网络连接不稳定" /><CandyAlert tone="error" title="连接失败，请重试" />{alertVisible ? <CandyAlert tone="success" title="房间创建成功！" closeLabel="Dismiss docs success alert" onClose={() => setAlertVisible(false)}>Invite a friend to get started.</CandyAlert> : <CandyButton size="sm" appearance="outline" onClick={() => setAlertVisible(true)}>Reset alert</CandyButton>}</>}
    {id === "navigation" && <><CandyNavigation aria-label="Docs game navigation" items={gameNavigation} value={nav} onChange={setNav} /><CandyNavigation aria-label="Docs sidebar navigation" items={gameNavigation.slice(0, 3)} value={nav} onChange={setNav} orientation="vertical" /><p className="reference-hint" role="status">Current destination: {nav}</p></>}
    {id === "breadcrumbs" && <CandyBreadcrumb aria-label="Docs breadcrumbs" items={[{ label: "首页", icon: <CandyGameIcon name="home" size={20} />, onClick: () => toast("Navigate home") }, { label: "设置", onClick: () => toast("Open settings") }, { label: "主题" }]} />}
    {id === "pagination" && <><CandyPagination aria-label="Docs pagination" page={page} totalPages={10} onPageChange={setPage} /><p className="reference-hint" role="status">Page {page} of 10</p></>}
    {id === "steps" && <><CandySteps aria-label="Docs setup steps" items={[{ label: "配置", description: "设置房间" }, { label: "主题", description: "选择主题" }, { label: "完成", description: "邀请朋友" }]} current={step} onStepChange={setStep} /><p className="reference-hint" role="status">Current step: {step + 1}</p><CandyButton size="sm" appearance="outline" onClick={() => setStep((value) => (value + 1) % 4)}>{step === 3 ? "Restart setup" : "Next step"}</CandyButton></>}
    {id === "dropdowns" && <><CandyDropdown trigger={<CandyButton size="sm" appearance="outline" variant="gray" leftIcon={<CandyAvatar size="xs" />} rightIcon={<CandyGameIcon name="arrow-down" size={15} />}>Player menu</CandyButton>} items={[{ id: "edit", label: "Edit profile", icon: <CandyGameIcon name="edit" size={18} />, onSelect: () => toast("Edit profile selected") }, { id: "settings", label: "Settings", icon: <CandyGameIcon name="settings" size={18} />, onSelect: () => toast("Settings selected") }, { id: "unavailable", label: "Unavailable", disabled: true }, { id: "logout", label: "Sign out", destructive: true, separator: true, onSelect: () => toast("Sign out demonstration") }]} /><p className="reference-hint">Try ArrowUp / ArrowDown, Home / End, Enter and Escape. Tab leaves the menu.</p></>}
    {id === "stepper" && <><CandyStepper label="Round duration (seconds)" value={seconds} onChange={setSeconds} min={30} max={300} step={10} /><p className="reference-hint" role="status">Round duration: {seconds}s</p><CandyStepper label="Read-only value" defaultValue={15} readOnly size="sm" /><CandyStepper label="Disabled value" defaultValue={10} disabled size="sm" /></>}
    {id === "tag-input" && <><CandyTagInput label="Favorite themes" value={tags} onChange={setTags} maxTags={6} maxTagLength={12} placeholder="Type a theme and press Enter…" /><p className="reference-hint" role="status">{tags.length} / 6 tags · Enter to add, Backspace to remove the last tag.</p></>}
    {id === "upload" && <><CandyFileUpload aria-label="Docs image upload" label="Click or drop images here" description="PNG or JPG · up to 1 MB each · 3 files maximum" accept="image/png,image/jpeg" multiple maxFiles={3} maxSize={1024 * 1024} onFilesChange={setFiles} /><p className="reference-hint" role="status">{files.length} accepted files. Local only; nothing is uploaded.</p></>}
    {id === "date-time" && <><div className="reference-two-columns"><CandyDatePicker label="Game date" value={date} onChange={(event) => setDate(event.target.value)} /><CandyTimePicker label="Start time" value={time} onChange={(event) => setTime(event.target.value)} /></div><p className="reference-hint" role="status">Scheduled for {date} at {time} · local demo</p></>}
    {id === "color-picker" && <><CandyColorPicker label="Theme color" value={color} onChange={setColor} hexLabel="Docs theme hex" /><div className="reference-color-sample"><span style={{ backgroundColor: color }} aria-hidden="true" /><code role="status">{color.toUpperCase()}</code></div></>}
    {id === "empty-states" && <CandyEmptyState title="还没有房间" description="创建第一个房间，邀请朋友一起开始吧。" icon={<CandyGameIcon name="controller" size={64} color="var(--candy-primary)" />} action={<CandyButton variant="yellow" onClick={() => toast("Create room selected")}>创建房间</CandyButton>} />}
    {id === "notifications" && (notificationVisible ? <CandyNotification title="New message" description="Your friends are ready to play." icon={<CandyGameIcon name="bell" size={30} color="#d69c00" />} closeLabel="Dismiss docs notification" onClose={() => setNotificationVisible(false)} action={<CandyButton size="sm" variant="ghost" onClick={() => toast("Messages marked as read")}>Read messages</CandyButton>} /> : <CandyButton appearance="outline" onClick={() => setNotificationVisible(true)}>Reset notification</CandyButton>)}
    {id === "social-buttons" && <><div className="reference-social-grid">{(["twitter", "google", "vk", "discord"] as CandySocialProvider[]).map((provider) => <CandySocialButton key={provider} provider={provider} size="sm" onClick={() => toast(`${provider} button demo; no login request was sent`)} />)}</div><p className="reference-hint">Presentation only. Connect your own authorized authentication flow.</p></>}
  </div>;
}